# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Abhinav Singh
email: sudo.abhinav@gmail.com
description:  I'm a student at JIIT, Noida. CSE 15-19
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://sudoabhinav.github.io" # the base hostname & protocol for your site

github_username:  sudoabhinav

# Build settings
markdown: kramdown
